# Generated by Django 5.2.1 on 2025-06-03 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('player', '球員搜尋'), ('team', '球隊搜尋'), ('game', '比賽搜尋')], max_length=20, verbose_name='搜尋類型')),
                ('search_query', models.CharField(max_length=200, verbose_name='搜尋關鍵字')),
                ('results_count', models.IntegerField(default=0, verbose_name='結果數量')),
                ('search_time', models.DateTimeField(auto_now_add=True, verbose_name='搜尋時間')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
            ],
            options={
                'verbose_name': '搜尋歷史',
                'verbose_name_plural': '搜尋歷史',
                'ordering': ['-search_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_id', models.IntegerField(help_text='MLB 官方 API 中的球隊識別碼', unique=True, verbose_name='MLB 球隊 ID')),
                ('name', models.CharField(help_text='球隊的完整名稱', max_length=100, verbose_name='球隊名稱')),
                ('abbreviation', models.CharField(help_text='球隊的縮寫代碼', max_length=5, verbose_name='球隊縮寫')),
                ('city', models.CharField(blank=True, help_text='球隊所在的城市', max_length=50, verbose_name='所在城市')),
                ('league', models.CharField(blank=True, help_text='球隊所屬的聯盟', max_length=50, verbose_name='聯盟')),
                ('division', models.CharField(blank=True, help_text='球隊所屬的分區', max_length=50, verbose_name='分區')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '球隊',
                'verbose_name_plural': '球隊',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_id', models.IntegerField(help_text='MLB 官方 API 中的球員識別碼', unique=True, verbose_name='MLB 球員 ID')),
                ('full_name', models.CharField(help_text='球員的完整姓名', max_length=100, verbose_name='球員姓名')),
                ('primary_position', models.CharField(choices=[('P', '投手'), ('C', '捕手'), ('1B', '一壘手'), ('2B', '二壘手'), ('3B', '三壘手'), ('SS', '游擊手'), ('LF', '左外野手'), ('CF', '中外野手'), ('RF', '右外野手'), ('DH', '指定打擊'), ('OF', '外野手'), ('IF', '內野手'), ('UT', '工具人')], help_text='球員的主要守備位置', max_length=3, verbose_name='主要位置')),
                ('photo', models.ImageField(blank=True, help_text='球員的照片', null=True, upload_to='player_photos/', verbose_name='球員照片')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('height_cm', models.IntegerField(blank=True, help_text='球員身高，單位為公分', null=True, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(250)], verbose_name='身高(公分)')),
                ('weight_kg', models.IntegerField(blank=True, help_text='球員體重，單位為公斤', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='體重(公斤)')),
                ('bat_hand', models.CharField(blank=True, choices=[('L', '左投左打'), ('R', '右投右打'), ('S', '右投左右開弓'), ('B', '左右投')], max_length=1, null=True, verbose_name='打擊慣用手')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('current_team', models.ForeignKey(blank=True, help_text='球員目前效力的球隊', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mlb_app.team', verbose_name='目前球隊')),
            ],
            options={
                'verbose_name': '球員',
                'verbose_name_plural': '球員',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(verbose_name='比賽日期')),
                ('is_home', models.BooleanField(default=True, help_text='是否為主場比賽', verbose_name='主場比賽')),
                ('at_bats', models.IntegerField(default=0, verbose_name='打數')),
                ('hits', models.IntegerField(default=0, verbose_name='安打數')),
                ('runs', models.IntegerField(default=0, verbose_name='得分')),
                ('rbi', models.IntegerField(default=0, verbose_name='打點')),
                ('home_runs', models.IntegerField(default=0, verbose_name='全壘打')),
                ('innings_pitched', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='投球局數')),
                ('strikeouts', models.IntegerField(default=0, verbose_name='三振數')),
                ('walks', models.IntegerField(default=0, verbose_name='保送數')),
                ('earned_runs', models.IntegerField(default=0, verbose_name='自責分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('player', models.ForeignKey(help_text='這場比賽的球員', on_delete=django.db.models.deletion.CASCADE, to='mlb_app.player', verbose_name='球員')),
                ('opponent_team', models.ForeignKey(help_text='這場比賽的對手', on_delete=django.db.models.deletion.CASCADE, to='mlb_app.team', verbose_name='對手球隊')),
            ],
            options={
                'verbose_name': '比賽記錄',
                'verbose_name_plural': '比賽記錄',
                'ordering': ['-game_date'],
                'unique_together': {('player', 'game_date', 'opponent_team')},
            },
        ),
    ]
